### ISSUE TITLE
Error occured when compile file IntegratedLSTMSegmentor.cpp

### ISSUE THREAD

**Issue by zjcerwin** [SUTDNLP/NNTransitionSegmentor#1]
error info:/model/IntegratedLSTMBeamSearcher.h:214:3: error: no matching function for call to LookupTable<mshadow::cpu>::initial(const nr::NRMat<double>&, bool)
I have looked into LibN3L "LookupTable.h", the  function prototype is "void initial(const NRMat<dtype>& wordEmb)" there is no parameter match the bool.
What`s the 'bool' parameter stands for?
Is it appropriate to delete the second parameter?

**Comment by zhangmeishan** [comment]
Oh, you can simply remove the second parameter. I had used it to determine whether the pretrained embeddings should be normalized first.

**Comment by ChijunZhang** [comment]
Thank you, I have compiled it successfully.
Another question,have you planned to write a python warpper for this program or 'N3L'.
Maybe it is more convenient to experiment on python instead of cpp.

**Comment by zhangmeishan** [comment]
will  not  write  a  Python wrapper,  on the  one hand  i  aim  for  special  cases  that  popular  NN  libs  difficult  to handle,  on  the  other  hand  i  do  not  have  much  time  for  it.  actually  cnn  is  much  similar  to  my  version  libn3l 2.0,  which  you  can  refer  to  github.com/zhangmeishan/.  i  have re-implemented  the  NNTranSegmentor.

**Comment by ChijunZhang** [comment]
Got it, I will also follow the project  libn3l 2.0
